### ISSUE TITLE
3g 

### ISSUE THREAD

**Issue by starkun** [Moyster/android_device_meizu_m2note#10]
I think that the radio became weaker since the 15-09-2016 bild, could you see ... (for me as a single change - removed Radio FM)

**Comment by Moyster** [comment]
I don't think it's related ;) removing radio FM and its' lib can't influence 3g reception :
"The dynamic library 'libmtkplayer.so' is used by
'libmediaplayerservice.so' to create FM Audio Player"
FM.apk + libmtkplayer + radio jni were removed but it was inactive as we had no FM chip nor radio firmware to load ;)

**Comment by Moyster** [comment]
Unrelated but maybe I have a "lead" for you there, are you from India or China ? It might be possible the firmware/modem (in /etc/firmware/ ) I use in this rom is not "region optimised", it's from the Global stock rom, you might want to try and use the firmware files from your regional stock rom and see if there's any improvement.
I've seen this for the porridge 3k, that has some ifdefs to use either the global or indian firmware files so maybe the ones in I/C roms gives a better signal for Asia/India/Russia users ;)

If you try this, let me know if this helped and if it works, consider making a flashable zip I can link to the rom topic ;)
