### ISSUE TITLE
Added first implementation of Flyme OS-style swipe-to-recents gesture

### ISSUE THREAD

**Issue by teik-off** [Moyster/android_device_meizu_m2note#12]
https://github.com/justmax437/android_frameworks_base/commit/ecbb113f5b7093e5478350e9a11bc81e7e3376de

**Comment by Moyster** [comment]
Thanks, great finding ! I'll keep that around but I'm trying to fix that damned mback button to work correctly first :angry:

**Comment by Moyster** [comment]
Back button almost fixed and if I can spare myself from maintaining one less repo (I use stock cyanogen's android_framework_base).
If anyone wants this feature, feel free to build it :)
