### ISSUE TITLE
Bug with usb otg

### ISSUE THREAD

**Issue by AlexLartsev19** [Moyster/android_device_meizu_m2note#13]
@moyster, if listen music and unplug usb otg, smartphone ~1.5-2sec rebate and music stops.

**Comment by Moyster** [comment]
send a logcat bro

**Comment by AlexLartsev19** [comment]
OK ;)

**Comment by AlexLartsev19** [comment]
It is a log :)
FIRMWARE: CM-12.1-b8( i tnink, that on b9 this bug too).
[2016-09-27-18-39-12.txt](https://github.com/Moyster/android_device_meizu_m2note/files/496003/2016-09-27-18-39-12.txt)

**Comment by Moyster** [comment]
"action: android.intent.action.MEDIA_UNMOUNTED path: /storage/usbotg"

Do you safely remove Usb OTG from the "storage" settings ?? I don't use OTG and I don't even have an otg cable, but I recently removed "ro.sys.persist.usbotg" from build.prop so people can safely remove their otg devices.
If that doesn't "fix" it, i'll try something in the next build ;)

**Comment by AlexLartsev19** [comment]
H,, if use safely remove, then some files can remove sometimes(M2n ->USB otg ->PC running on Linux) :c. And becuase i don't use "Safely remove".

**Comment by Moyster** [comment]
When you remove "safely" and files disapear from the phone, did you try to reboot ? It seems cm-12.1 have/had that bug with mtp, tell if that works ;)

**Comment by Moyster** [comment]
https://github.com/Moyster/android_device_meizu_m2note/commit/59ea9a286793f4bab490680993823146e6c2f06b 
this might improve the situation a bit if you don't use fat32 usb keys, I'll make a new release soon

**Comment by AlexLartsev19** [comment]
Yap, it's cool, very cool! :D
