### ISSUE TITLE
Wifi hotspot

### ISSUE THREAD

**Issue by teik-off** [Moyster/android_device_meizu_m2note#17]
https://github.com/divis1969/android_system_netd/commit/5cb001a0122ad5318da21dfcd3ab98624f90efb1

**Comment by Moyster** [comment]
https://github.com/Moyster/android_device_mt6753_common/blob/cm-12.1/patches/system_netd/hotpost-fix.patch
Hello, Thanks for that but it's already in :) I made a bit of progress the latest days but it's still not properly working, I updated the binary blobs from 5.1.10G, I'm curious to know why wifi P2P (casting to a TV) works but not wifi hotspot.

**Comment by Moyster** [comment]
Updating blobs seems to fix the problem, I think that's either related to bin/hostapd or the wifi libs.
I'll close that, next build will have working hotspot (I tried both unsecured and secured AP, could connect and browse internet)

**Comment by teik-off** [comment]
It is very good!
