### ISSUE TITLE
MMS acting weirdly

### ISSUE THREAD

**Issue by robotx** [Moyster/android_device_meizu_m2note#36]
Hello,
First, my MMS were working perfectly before I switched to Cyanogenmod.
I am running the Elpun build, I tried to reinstall it multiple times but it still isn't working.
My MMS are working only at 10:14 p.m to be exact, and another time at night around 5 a.m.
Excepted these hours, I can't receive nor send any MMS.
I tried to find a way to provide the mms logs but it's on a level far too high from mine as google doesn't provide the documentation about this.
I am on a french operator called free if this helps.
Would someone mind about this issue?

**Comment by Moyster** [comment]
Hello,

Did you check your APNs ? I constatly wierd problems with MMS on Sfr/Free from time to time, unrelated to what device I uses, most of the time it can be sorted like that, but check you also enabled "data".

(PS: I often blamed SFR for this in the past, seems to be only a french thing, If anybody has any idea about wtf, or else I'm not able to do much)

Logs are displayed in logcat most of the time, try making a logcat trace when you send/receive a MMS ;)

**Comment by robotx** [comment]
Hello,

I solved the issue thanks to makuu on your CM thread who told us to try merging our APNs together.
I've followed these short instructions for info. 
http://forum.xda-developers.com/xperia-sp/general/merging-internet-mms-apns-lb-cm12-5-0-2-t3074482

Thanks for the help !

**Comment by Moyster** [comment]
:)
