### ISSUE TITLE
[DUPLICATE] Casting screen does not work

### ISSUE THREAD

**Issue by hellenicsun** [Moyster/android_device_meizu_m2note#42]
Without being totally sure it's ROM related, both integrated cast screen option in quick settings and Google Home app option do not work. When I press to cast screen, TV (to which a Chromecast dongle is connected) blacks for a sec and then it gets back to standby mode which means that cast screen services tried and failed. Any thoughts? I could provide a log if you tell me how.

**Comment by Moyster** [comment]
"adb logcat -C > log.txt" should work if you have adb working ;)

**Comment by franci22** [comment]
There is a similar problem [here](https://github.com/Moyster/android_device_meizu_m2note/issues/32)

**Comment by Moyster** [comment]
The need for logs is still real, although I could do it myself, I'd prefer having a logcat to parse and see if I can do something, instead of setting the mood to try and fix things I can't. :)
