### ISSUE TITLE
Bluetooth problem on CM13.0

### ISSUE THREAD

**Issue by aftersilence** [Moyster/android_device_meizu_m2note#45]
There are some problems with bluettoh on cm13.0: pairing with any other devices doesnt work so bluetooth is not usable here. Thx for your work.

**Comment by VNGXR** [comment]
Pairing works just fine for me. Tested with i9300 and Mi Band 2 :)

**Comment by Moyster** [comment]
(I'm around but I lack the time to properly release a MM device tree, so bugs/issues will be tracked on the new one, the 404 link from my thread is not a real "404", it's just my laziness :D )

But yeah, bluetooth is unstable but I tested simple features (pairing to my smartwatch, "ok google", Eleven/Google Music controls finally works).

I guess I should create that new repo for clarity / bug reps ;)

**Comment by aftersilence** [comment]
Fixed by rom reflashing with full wipe, need to check now how it will work with my car multimedia system..

**Comment by Moyster** [comment]
Oh well, good to know gps / bt / stuff are not broken.

Bt is unstable and I'll work on it soon (tm), if you can't pair, reboot the phone (there's something crashing that prevents pairing, but if it pairs, it works fine)

**Comment by aftersilence** [comment]
Sorry, it was noobish mistakes :-) 
I will send a logcat with errors if I will find some.

**Comment by Moyster** [comment]
Np, I knew Bt was unstable, and I couldn't find the time to shout on you earlier, so I'm not mad anymore :)
