### ISSUE TITLE
Wifi hotspot doesn't work

### ISSUE THREAD

**Issue by Moyster** [Moyster/android_device_meizu_m2note#9]

**Comment by Gargarospo** [comment]
Eagerly waiting for this fix. I'd help if I only had a clue about how to work on an Android ROM.

**Comment by mrJericoJose** [comment]
Hoping to see the Fix for this next Beta Update. 😉 Thank you Moyster!

**Comment by Moyster** [comment]
Seriously, IF I knew how to fix that damn wifi hotspot, It'll be fixed already, it's an issue tracker not facebook, if you want to share your advice, there is already a thread for that on XDA you can CONTRIBUTE TO.

Do people at least REALISE how it especially is NOT ENJOYABLE to be stalked and asked for fixes, be it if my nickname appears on a website or if my mail is shown on my github page... or if I leave an ISSUE TRACKER open.
Seriously get your things together, I'm human, there's about 20 answers everyday on XDA, at least the same MP amount and then both my EMAIL ADRESS and my GITHUB is litteraly SPAMMED.

All I do, I do it for me, I own that phone, I don't use XYZ features, if you can't PATIENTLY WAIT then learn how to do it yourself.
